# Generated by Django 4.0.3 on 2022-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.CharField(max_length=100)),
                ('sales', models.CharField(max_length=100)),
                ('profits', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('expected', models.CharField(max_length=100)),
                ('o_chan', models.CharField(max_length=100)),
                ('deposit', models.CharField(max_length=100)),
                ('orders', models.CharField(max_length=100)),
            ],
        ),
    ]
